### ISSUE TITLE
ph type dmenu to stdout

### ISSUE THREAD

**Issue by chuugar** [purdueLUG/passhole#1]
Hi,
If use `ph type dmenu` in a terminal window, the password will be set indeed to the clipboard but also the password will be shown cleary to stdout .
Could you please fix that ?

Thanks.
I love the concept of passhole btw

**Comment by Evidlo** [comment]
I think you might be misunderstanding the purpose of of the `type` command.  It doesn't copy anything to the clipboard or send it to stdout.  It actually pretends to be a user typing on the keyboard and is intended to be invoked with a keyboard shortcut.

For example, on my system with i3wm, I do the following steps when logging on a website:

1. Select the login form in my browser.
2. Hit `Mod p` (which is configured to launch `ph type dmenu`)
3. Select the correct entry with dmenu.

Then `passhole` sends the password to the keyboard and fills in the password field for me.

**Comment by Evidlo** [comment]
I added an example of this for i3 at the bottom of the readme.

**Comment by chuugar** [comment]
Ok, my bad. That's fine with the example
