### ISSUE TITLE
Consider replacing the current password wordlist by the improved EFF Diceware one

### ISSUE THREAD

**Issue by jherazob** [purdueLUG/passhole#3]
The [Diceware wordlists](http://world.std.com/~reinhold/diceware.html) are crafted to be systematically generated with a known entropy level (using dice, but that's not relevant for this project), and generating passphrases using enough words from it they're uncrackable in practice. The issue is that those wordlists have bad usability, having short, nonsense or strange words, and profanity which may not be good for some uses. The wordlist used in this project shares these issues.

The EFF released [an alternate wordlist](https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases) that helps a lot with these problems, keeping the entropy high while still being easier to use by people and being safer for work.

The [actual file](https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt) is a bit bigger than the wordlist currently being used in this project by virtue of having a minimum word length as part of the usability improvements. 

Alternatively, in the same release they gave out two different wordlists, [one optimized for shorter words](https://www.eff.org/files/2016/09/08/eff_short_wordlist_1.txt) and [another optimized for autocompletion and easy typing](https://www.eff.org/files/2016/09/08/eff_short_wordlist_2_0.txt) (probably for mobile app usage). Maybe one of these may be interesting for the project.

**Comment by Evidlo** [comment]
The long list looks good.  The current wordlist has a bunch of weird entries like `aa`, `ye`, and `wc`.

The article recommends 77 bits of entropy per password, but isn't that a bit overkill?  Right now with the 10k wordlist were getting 66 bits at 5 words (64 bits with the dice wordlist).

**Comment by jherazob** [comment]
Yeah, as soon as i looked at the wordlist and saw those entries i remembered that one, easier to digest so to speak.
As for the entropy, it depends on the specific purpose. If the new password is for a forum for fans of Series X it shouldn't need to be very strong (worst case scenario they impersonate you on a forum), but for your main email it should be (worst case scenario is full identity theft). The original Diceware author [has an entry on this on his FAQ](http://world.std.com/~reinhold/dicewarefaq.html#howlong) explaining the general reasoning about this. But i'm all for overkill myself, if the software is going to be the one in charge of remembering them why not go with "too damn much"? :)

**Comment by Evidlo** [comment]
Implemented by b5c85f3ff2f44186734d33e4e882bf6bd8fd60ac
