### ISSUE TITLE
Dmenu Mode - Appears to have issues with special characters

### ISSUE THREAD

**Issue by ejhobbs** [purdueLUG/passhole#7]
I'm using passhole in dmenu mode with i3 (for the most part, works brilliant great stuff). However, I appear to be having some issues with passwords that have special characters. For example, one of my passwords appears to lock the shift key on, and then only prints out the first few characters.

I'm happy to look into this issue myself, however any guidance on where I should start looking would be appreciated.

**Comment by Evidlo** [comment]
I made a new branch called `pynput` that uses a different typing library.  Try that out and tell me how it goes.

**Comment by ejhobbs** [comment]
Just tried out the `pynput` branch, seems to have the same issue. FWIW I'm using python 3.6.4 and these are the installed versions of packages as per `pip list`: 

    Package         Version
    --------------- -------
    anytree         2.4.3
    appdirs         1.4.3
    Beaker          1.8.1
    colorama        0.3.9
    easypysmb       1.4.3
    future          0.16.0
    libkeepass      0.2.0
    louis           3.5.0
    lxml            4.1.1
    Mako            1.0.7
    MarkupSafe      1.0
    nose            1.3.7 
    packaging       16.8
    passhole        1.5.5
    pip             9.0.1
    pyasn1          0.4.2
    pycrypto        2.6.1
    Pygments        2.2.0
    pygpgme         0.3
    pykeepass       2.8.1
    pynput          1.3.10
    pyparsing       2.2.0
    pyserial        3.4
    pysmb           1.1.22
    python-dateutil 2.7.3
    python-xlib     0.23
    PyUserInput     0.1.12
    setuptools      39.0.1
    six             1.11.0

From what I can see, it looks as though there could be something in the string that's confusing pynput /pykeyboard into pressing modifier keys but I'm not sure.

**Comment by Evidlo** [comment]
Can you give me a sample of a username/password combo that does what you
say?

**Comment by Evidlo** [comment]
Or better, a .kdbx that I can test on uploaded to [gist.github.com]()

**Comment by Evidlo** [comment]
Still haven't been able to reproduce this issue.

**Comment by ejhobbs** [comment]
My apologies, had a busy weekend. Will try to get a kbdx uploaded for this evening, thanks for your help so far 😄

**Comment by ejhobbs** [comment]
I've uploaded the file here: https://gist.github.com/ejhobbs/c1707ed578388b8e162b0fdbf7dae3b3

It contains two users, neither of which are not typed correctly in dmenu mode

**Comment by Evidlo** [comment]
I added a ``--xdotool`` option to the `type` command which switches to xdotool as an output method.

**Comment by ejhobbs** [comment]
Hi, sorry for the delay. It does appear to be an issue with xdotool, however thankfully I no longer use the service that xdotool had an issue with so all appears to work great now! You can close this ticket 🙂
